#pragma once

#include "types.hpp"

// Abstract hardware interface.
//
// This interface separates control logic from the concrete implementation
// of sensors, actuators, and simulation backends.
//

class IElevatorHardware {
public:
    virtual ~IElevatorHardware() = default;

    // Read current hardware input signals.
    virtual Inputs readInputs() = 0;

    // Return the current elevator floor according to the hardware model.
    virtual int currentFloor() const = 0;

    // Check whether the elevator is currently positioned at a given floor.
    virtual bool isAtFloor(int floor) const = 0;

    // Apply output signals generated by the controller.
    virtual void applyOutputs(const Outputs& outputs) = 0;
};